// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Budget.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionResponseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount property</summary>
        public double? Amount { get; set; }
        /// <summary>The authorizationCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationCode { get; set; }
#nullable restore
#else
        public string AuthorizationCode { get; set; }
#endif
        /// <summary>The cashbackForDate property</summary>
        public Date? CashbackForDate { get; set; }
        /// <summary>The dateTransaction property</summary>
        public Date? DateTransaction { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The followNumber property</summary>
        public int? FollowNumber { get; set; }
        /// <summary>The iban property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Iban { get; set; }
#nullable restore
#else
        public string Iban { get; set; }
#endif
        /// <summary>The ibanOtherParty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IbanOtherParty { get; set; }
#nullable restore
#else
        public string IbanOtherParty { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The nameOtherParty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameOtherParty { get; set; }
#nullable restore
#else
        public string NameOtherParty { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Budget.ApiClient.Models.TransactionResponseModel"/> and sets the default values.
        /// </summary>
        public TransactionResponseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Budget.ApiClient.Models.TransactionResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Budget.ApiClient.Models.TransactionResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Budget.ApiClient.Models.TransactionResponseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "authorizationCode", n => { AuthorizationCode = n.GetStringValue(); } },
                { "cashbackForDate", n => { CashbackForDate = n.GetDateValue(); } },
                { "dateTransaction", n => { DateTransaction = n.GetDateValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "followNumber", n => { FollowNumber = n.GetIntValue(); } },
                { "iban", n => { Iban = n.GetStringValue(); } },
                { "ibanOtherParty", n => { IbanOtherParty = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "nameOtherParty", n => { NameOtherParty = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteStringValue("authorizationCode", AuthorizationCode);
            writer.WriteDateValue("cashbackForDate", CashbackForDate);
            writer.WriteDateValue("dateTransaction", DateTransaction);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("followNumber", FollowNumber);
            writer.WriteStringValue("iban", Iban);
            writer.WriteStringValue("ibanOtherParty", IbanOtherParty);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("nameOtherParty", NameOtherParty);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
