# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool: Default

container: 'mcr.microsoft.com/dotnet/sdk:8.0' 

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: CmdLine@2
  displayName: 'Restore'
  inputs:
    script: 'dotnet restore $(solution)'

- task: CmdLine@2
  displayName: 'Build'
  inputs:
    script: 'dotnet build $(solution)'

- task: CmdLine@2
  displayName: 'Test'
  inputs:
    script: 'dotnet test $(solution)'



