trigger:
  branches:
   include:
     - main
  paths:
   include:
     - Budget.App/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: 'Budget.App/Budget.App.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--no-restore -c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--no-restore --no-build'
    modifyOutputPath: false

- task: PublishPipelineArtifact@1
  displayName: 'Upload artefacts'
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'