trigger:
  branches:
   include:
     - main
  paths:
   include:
     - Budget.Htmx/*
     - azure-pipelines-app.yml

pool:
  vmImage: 'windows-latest'
  name: Default

variables:
  solution: '**/*.sln'
  project: 'Budget.Htmx'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactPath: '$(System.DefaultWorkingDirectory)/drop'
  branchName: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet tool install --global Versionize && git config --global user.name "$(git_name)" && git config --global user.email "$(git_email)"
  displayName: 'Install Versionize'

- script: git checkout $(branchName) && git reset origin/$(branchName) --hard && cd $(project) && versionize --commit-suffix "[skip ci]" && git push --follow-tags origin $(branchName)
  displayName: 'Bump project version'
  
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    restoreArguments: '--locked-mode'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--no-restore -c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--no-restore --no-build -o $(artifactPath)'
    modifyOutputPath: false

- publish: '$(artifactPath)'
  artifact: WebApp