trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Budget.Api/*
      - Budget.ApiClient/*
      - azure-pipelines-api2.yml

pool:
  vmImage: 'windows-latest'
  name: Default

variables:
  solution: '**/*.sln'
  project: 'Budget.Api'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactPath: '$(System.DefaultWorkingDirectory)/drop'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(project)'
    restoreArguments: '--locked-mode'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--no-restore -c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--no-restore --no-build -o $(artifactPath)'
    modifyOutputPath: false

- publish: '$(artifactPath)'
  artifact: WebApi