version: '3.8'
services:
  budget:
    image: registry.timo-hermans.nl/budget:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:8080"
    networks:
      - server
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sparen.rule=HOST(`sparen.timo-hermans.nl`)'
      - 'traefik.http.services.sparen.loadbalancer.server.port=8080'

networks:
  server:
    external: true