services:
  budget:
    container_name: budget
    image: registry.timo-hermans.nl/budget:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik
      - postgres
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.budget.rule=HOST(`budget.timo-hermans.nl`)'
      - 'traefik.http.services.budget.loadbalancer.server.port=8080'

networks:
  postgres:
    name: postgres
    external: true
  traefik:
    external: true
