// <auto-generated/>
#pragma warning disable CS0618
using Budget.ApiClient.Transactions.Item.CashbackDate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Budget.ApiClient.Transactions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Transactions\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cashbackDate property</summary>
        public global::Budget.ApiClient.Transactions.Item.CashbackDate.CashbackDateRequestBuilder CashbackDate
        {
            get => new global::Budget.ApiClient.Transactions.Item.CashbackDate.CashbackDateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Budget.ApiClient.Transactions.Item.TransactionsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Transactions/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Budget.ApiClient.Transactions.Item.TransactionsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Transactions/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
