@Budget_Api_HostAddress = http://localhost:5280
@keycloak_url = https://auth.timo-hermans.nl
@realm = home
@client_id = budget_api
@client_secret = BclXqFoEoaIcfqHkIVeYWCJCxMWP9pH7


### Get Access Token
# @name login
POST {{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&grant_type=client_credentials

###

GET {{Budget_Api_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

###

POST {{Budget_Api_HostAddress}}/transactions/upload
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: multipart/form-data; boundary=FileBoundary

--FileBoundary
Content-Disposition: form-data; name="file"; filename="transactions-test.csv"
Content-Type: text/csv

< ./transactions-test.csv
--FileBoundary--

###

GET {{Budget_Api_HostAddress}}/transactions?startDate=2025-03-01&endDate=2025-05-01
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

###

GET {{Budget_Api_HostAddress}}/transactions/ibans
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}

###

GET {{Budget_Api_HostAddress}}/transactions/cashflow-per-iban
Accept: application/json
Authorization: Bearer {{login.response.body.access_token}}