// <auto-generated/>
#pragma warning disable CS0618
using Budget.ApiClient.TransactionsFileJob.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Budget.ApiClient.TransactionsFileJob
{
    /// <summary>
    /// Builds and executes requests for operations under \TransactionsFileJob
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsFileJobRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Budget.ApiClient.TransactionsFileJob.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Budget.ApiClient.TransactionsFileJob.Item.TransactionsFileJobItemRequestBuilder"/></returns>
        public global::Budget.ApiClient.TransactionsFileJob.Item.TransactionsFileJobItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Budget.ApiClient.TransactionsFileJob.Item.TransactionsFileJobItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Budget.ApiClient.TransactionsFileJob.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Budget.ApiClient.TransactionsFileJob.Item.TransactionsFileJobItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Budget.ApiClient.TransactionsFileJob.Item.TransactionsFileJobItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Budget.ApiClient.TransactionsFileJob.Item.TransactionsFileJobItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Budget.ApiClient.TransactionsFileJob.TransactionsFileJobRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsFileJobRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TransactionsFileJob", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Budget.ApiClient.TransactionsFileJob.TransactionsFileJobRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsFileJobRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TransactionsFileJob", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
