name: Budget Angular

on:
  push:
    paths: 
    - 'src/budget-angular/**'
    - '.github/workflows/budget-angular.yaml'
    - '.github/workflows/_angular_template.yaml'
    branches: [ "main" ]
  workflow_dispatch:
      
jobs:
  angular_build_and_deploy:
    uses: ./.github/workflows/_angular_template.yml
    with:
      project_path: 'src/budget-angular'
      image_name: 'budget-angular'
      deployment_path: 'k8s/budget/frontend-angular/deployment.yaml'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
