name: Trigger auto deployment for budget

# When this action will be executed
on:
  workflow_run:
    branches: [ main ]
    workflows: [ .NET ]
    types:
      - completed

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BUDGET_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BUDGET_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BUDGET_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: docker.io
          registryUsername: ${{ secrets.BUDGET_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BUDGET_REGISTRY_PASSWORD }}
          containerAppName: budget
          resourceGroup: Budget
          imageToBuild: itsyou0o/budget:${{ github.sha }}
          dockerfilePath: Budget.Pages/Dockerfile


