name: Deployment on home server

# When this action will be executed
on:
  push:
    branches:
      - home

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/home' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == '.NET'
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Budget.Pages/Dockerfile --tag ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget
      - name: Tag Image Commit sha
        run: docker tag ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget:${{github.sha}}
      - name: Tag Image Latest
        run: docker tag ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget:latest
      - name: Login To Registry
        run: echo "${{secrets.HOME_BUDGET_REGISTRY_PASSWORD}}" | docker login -u ${{secrets.HOME_BUDGET_REGISTRY_USERNAME}} --password-stdin ${{secrets.HOME_BUDGET_REGISTRY_HOST}}
      - name: Push To Registry
        run: docker push -a ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget
