# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI and CD

on: push

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
  
  unit-test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: cd Budget.Tests && dotnet test --verbosity normal
        
  integration-test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: cd Budget.IntegrationTests && dotnet test --verbosity normal
        
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test]
    if: github.ref == 'refs/heads/home' && ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Budget.Pages/Dockerfile --tag ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget
      - name: Tag Image Commit sha
        run: docker tag ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget:${{github.sha}}
      - name: Tag Image Latest
        run: docker tag ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget:latest
      - name: Login To Registry
        run: echo "${{secrets.HOME_BUDGET_REGISTRY_PASSWORD}}" | docker login -u ${{secrets.HOME_BUDGET_REGISTRY_USERNAME}} --password-stdin ${{secrets.HOME_BUDGET_REGISTRY_HOST}}
      - name: Push To Registry
        run: docker push -a ${{secrets.HOME_BUDGET_REGISTRY_HOST}}/budget
