# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: UI

on:
  push:
    paths: 
    - 'src/Budget.Ui/**'
    - 'tests/Budget.Ui.*/**'
    branches: [ "main" ]
  workflow_dispatch:
      
jobs:
  cluster_build_and_deploy:
    uses: ./.github/workflows/_template.yml
    with:
      project_path: 'src/Budget.Ui'
      tests_path: 'tests/Budget.Ui*'
      image_name: 'budget-app'
      deployment_path: 'k8s/budget/frontend/deployment.yaml'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}