# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: UI

env:
  PROJECT_PATH: 'src/Budget.Ui'
  TESTS_PATH: 'tests/Budget.Ui*'

on:
  push:
    paths: 
    - 'src/Budget.Ui/**'
    - 'tests/Budget.Ui.*/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT_PATH
    - name: Build
      run: dotnet build $PROJECT_PATH --no-restore
    - name: Test
      run: dotnet test $TESTS_PATH --verbosity normal
