# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Worker

on:
  push:
    paths: 
    - 'src/Budget.Worker/**'
    - 'src/Budget.Application/**'
    - 'src/Budget.Domain/**'
    - 'src/Budget.Infrastructure/**'
    branches: [ "main" ]
  workflow_dispatch:
      
jobs:
  cluster_build_and_deploy:
    uses: ./.github/workflows/_template.yml
    with:
      project_path: 'src/Budget.Worker'
      tests_path: 'tests/Budget.Api.UnitTests'
      image_name: 'budget-worker'
      deployment_path: 'k8s/budget/backend/deployment.yaml'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}